version: 2
jobs:
    build:
        docker:
            - image: debian:stretch

        steps:
            - checkout

            - run:
                name: Install sudo
                command: apt update && apt install -y sudo && rm -rf /var/lib/apt/lists/*

            - run:
                name: Install clang
                command: sudo apt install -y clang

            - run:
                name: Install scons
                command: sudo apt install -y scons

            - run:
                name: Build
                command: scons

            - run:
                name: Run
                command: build/dane
