version: 2
jobs:
    build:
        docker:
            - image: debian:stretch

        steps:
            - checkout

            - run:
                name: Setup
                command: |
                    apt update
                    apt install -y clang
                    apt install -y scons

            - run:
                name: Build
                command: scons

            - run:
                name: Run
                command: build/dane
