version: 2
jobs:
    build:
        docker:
            - image: dan1994/cpp-build-env:1

        steps:
            - checkout

            - run:
                name: Build
                command: scons .

            - run:
                name: Unit Test
                command: build/test/gtest

            - run:
                name: Run
                command: build/debug/dane
